# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\aboutus.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import aboutus


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(563, 0)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color : rgb(255, 218, 212)")
        self.name3 = QtWidgets.QPushButton(Dialog)
        self.name3.setGeometry(QtCore.QRect(90, 280, 381, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name3.setFont(font)
        self.name3.setStyleSheet("QPushButton {\n"
"    font: 14pt \"MS Shell Dlg 2\";        \n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #0000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QPushButton:hover:pressed\n"
"{\n"
"  border: 2px solid rgb(255, 73, 73);\n"
"}")
        self.name3.setObjectName("name3")
        self.image1 = QtWidgets.QLabel(Dialog)
        self.image1.setGeometry(QtCore.QRect(-10, 310, 181, 161))
        self.image1.setStyleSheet("image: url(:/image/icons.png);")
        self.image1.setText("")
        self.image1.setObjectName("image1")
        self.image2 = QtWidgets.QLabel(Dialog)
        self.image2.setGeometry(QtCore.QRect(430, 20, 101, 71))
        self.image2.setStyleSheet("image: url(:/image/stars.png);\n"
"")
        self.image2.setText("")
        self.image2.setObjectName("image2")
        self.name1 = QtWidgets.QPushButton(Dialog)
        self.name1.setGeometry(QtCore.QRect(90, 140, 381, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name1.setFont(font)
        self.name1.setStyleSheet("QPushButton {\n"
"    font: 14pt \"MS Shell Dlg 2\";        \n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #0000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QPushButton:hover:pressed\n"
"{\n"
"  border: 2px solid rgb(255, 73, 73);\n"
"}")
        self.name1.setObjectName("name1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 40, 221, 61))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet("QLabel {    \n"
"    color: #0000;\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.name2 = QtWidgets.QPushButton(Dialog)
        self.name2.setGeometry(QtCore.QRect(90, 210, 381, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name2.setFont(font)
        self.name2.setStyleSheet("QPushButton {\n"
"    font: 14pt \"MS Shell Dlg 2\";        \n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #0000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QPushButton:hover:pressed\n"
"{\n"
"  border: 2px solid rgb(255, 73, 73);\n"
"}")
        self.name2.setObjectName("name2")
        self.closeBotton = QtWidgets.QPushButton(Dialog)
        self.closeBotton.setGeometry(QtCore.QRect(210, 370, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.closeBotton.setFont(font)
        self.closeBotton.setStyleSheet("QPushButton {\n"
"    font: 18pt \"MS Shell Dlg 2\";        \n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #0000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QPushButton:hover:pressed\n"
"{\n"
"  border: 2px solid rgb(255, 73, 73);\n"
"}")
        self.closeBotton.setObjectName("closeBotton")
        self.image2.raise_()
        self.image1.raise_()
        self.name3.raise_()
        self.name1.raise_()
        self.label.raise_()
        self.name2.raise_()
        self.closeBotton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Aboutus"))
        self.name3.setText(_translate("Dialog", "นายแสงชัย จันหอม 116310400514-0"))
        self.name1.setText(_translate("Dialog", "นางสาวณัฐพร กอซอ 116310462001-3"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">About us</span></p></body></html>"))
        self.name2.setText(_translate("Dialog", "นายศุภุณัฐ สุขะวัฒนะ 116310462017-9"))
        self.closeBotton.setText(_translate("Dialog", "ออก"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
