# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jedzpetch\Desktop\Python\ui\editorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editorder(object):
    def setupUi(self, editorder):
        editorder.setObjectName("editorder")
        editorder.resize(699, 458)
        editorder.setMinimumSize(QtCore.QSize(699, 458))
        editorder.setMaximumSize(QtCore.QSize(699, 458))
        editorder.setStyleSheet("background-color : rgb(255, 218, 212)")
        self.menu = QtWidgets.QLabel(editorder)
        self.menu.setGeometry(QtCore.QRect(20, 90, 121, 41))
        self.menu.setObjectName("menu")
        self.price = QtWidgets.QLabel(editorder)
        self.price.setGeometry(QtCore.QRect(40, 210, 91, 51))
        self.price.setObjectName("price")
        self.editButton = QtWidgets.QPushButton(editorder)
        self.editButton.setGeometry(QtCore.QRect(20, 310, 181, 81))
        self.editButton.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"background-color : rgb(255, 216, 215)")
        self.editButton.setObjectName("editButton")
        self.image1_2 = QtWidgets.QLabel(editorder)
        self.image1_2.setGeometry(QtCore.QRect(490, 270, 181, 161))
        self.image1_2.setMaximumSize(QtCore.QSize(181, 161))
        self.image1_2.setStyleSheet("image: url(:/image/icon.png);")
        self.image1_2.setText("")
        self.image1_2.setObjectName("image1_2")
        self.addid = QtWidgets.QLineEdit(editorder)
        self.addid.setGeometry(QtCore.QRect(160, 30, 251, 41))
        self.addid.setObjectName("addid")
        self.adddetails = QtWidgets.QLineEdit(editorder)
        self.adddetails.setGeometry(QtCore.QRect(160, 150, 251, 41))
        self.adddetails.setObjectName("adddetails")
        self.addprice = QtWidgets.QLineEdit(editorder)
        self.addprice.setGeometry(QtCore.QRect(160, 220, 251, 41))
        self.addprice.setObjectName("addprice")
        self.ID = QtWidgets.QLabel(editorder)
        self.ID.setGeometry(QtCore.QRect(60, 40, 61, 41))
        self.ID.setObjectName("ID")
        self.details = QtWidgets.QLabel(editorder)
        self.details.setGeometry(QtCore.QRect(10, 150, 141, 51))
        self.details.setObjectName("details")
        self.addmenu = QtWidgets.QLineEdit(editorder)
        self.addmenu.setGeometry(QtCore.QRect(160, 90, 251, 41))
        self.addmenu.setObjectName("addmenu")
        self.delButton = QtWidgets.QPushButton(editorder)
        self.delButton.setGeometry(QtCore.QRect(240, 310, 181, 81))
        self.delButton.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"background-color : rgb(255, 216, 215)")
        self.delButton.setObjectName("delButton")
        self.searchButton = QtWidgets.QPushButton(editorder)
        self.searchButton.setGeometry(QtCore.QRect(440, 30, 101, 41))
        self.searchButton.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"background-color : rgb(255, 216, 215)")
        self.searchButton.setObjectName("searchButton")

        self.retranslateUi(editorder)
        QtCore.QMetaObject.connectSlotsByName(editorder)

    def retranslateUi(self, editorder):
        _translate = QtCore.QCoreApplication.translate
        editorder.setWindowTitle(_translate("editorder", "Dialog"))
        self.menu.setText(_translate("editorder", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">ชื่อสินค้า :</span></p></body></html>"))
        self.price.setText(_translate("editorder", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">ราคา    :</span></p></body></html>"))
        self.editButton.setText(_translate("editorder", "แก้ไขรายการ"))
        self.ID.setText(_translate("editorder", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">ID :</span></p></body></html>"))
        self.details.setText(_translate("editorder", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">รายละเอียด :</span></p></body></html>"))
        self.delButton.setText(_translate("editorder", "ลบรายการ"))
        self.searchButton.setText(_translate("editorder", "ค้นหา"))
