# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jedzpetch\Desktop\Python\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(563, 499)
        Dialog.setMinimumSize(QtCore.QSize(563, 0))
        Dialog.setMaximumSize(QtCore.QSize(563, 499))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Jedzpetch\\Desktop\\Python\\ui\\../../resorce/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color : rgb(255, 218, 212)")
        self.loginButton = QtWidgets.QPushButton(Dialog)
        self.loginButton.setGeometry(QtCore.QRect(210, 330, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton {\n"
"    font: 18pt \"MS Shell Dlg 2\";    \n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #0000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QPushButton:hover:pressed\n"
"{\n"
"  border: 2px solid rgb(255, 73, 73);\n"
"}\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 60, 221, 61))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet("QLabel {    \n"
"    color: #0000;\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.passwordText = QtWidgets.QLineEdit(Dialog)
        self.passwordText.setGeometry(QtCore.QRect(100, 240, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Cloud Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.passwordText.setFont(font)
        self.passwordText.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #0000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.passwordText.setObjectName("passwordText")
        self.image2 = QtWidgets.QLabel(Dialog)
        self.image2.setGeometry(QtCore.QRect(410, 10, 101, 71))
        self.image2.setStyleSheet("image: url(:/image/stars.png);")
        self.image2.setText("")
        self.image2.setObjectName("image2")
        self.usernameText = QtWidgets.QLineEdit(Dialog)
        self.usernameText.setGeometry(QtCore.QRect(100, 170, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Cloud Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.usernameText.setFont(font)
        self.usernameText.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #0000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.usernameText.setObjectName("usernameText")
        self.image1 = QtWidgets.QLabel(Dialog)
        self.image1.setGeometry(QtCore.QRect(0, 290, 181, 161))
        self.image1.setStyleSheet("image: url(:/image/icons.png);")
        self.image1.setText("")
        self.image1.setObjectName("image1")
        self.image1_2 = QtWidgets.QLabel(Dialog)
        self.image1_2.setGeometry(QtCore.QRect(380, 290, 181, 161))
        self.image1_2.setMaximumSize(QtCore.QSize(181, 161))
        self.image1_2.setStyleSheet("image: url(:/image/icon.png);")
        self.image1_2.setText("")
        self.image1_2.setObjectName("image1_2")
        self.image2.raise_()
        self.image1_2.raise_()
        self.image1.raise_()
        self.loginButton.raise_()
        self.label.raise_()
        self.passwordText.raise_()
        self.usernameText.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "เข้าสู่ระบบ"))
        self.loginButton.setText(_translate("Dialog", "เข้าสู่ระบบ"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">เข้าสู่ระบบ</span></p></body></html>"))
        self.passwordText.setPlaceholderText(_translate("Dialog", "Password"))
        self.usernameText.setPlaceholderText(_translate("Dialog", "Username"))
